apiVersion: v1
kind: Pod
metadata:
  name: mongodb-1
  namespace: default
  labels:
    app: mongodb1
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: my-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: my-password
        - name: MONGO_INITDB_DATABASE
          value: "my-db"
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-2
  namespace: default
  labels:
    app: mongodb2
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: my-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: my-password
        - name: MONGO_INITDB_DATABASE
          value: "my-db"