apiVersion: v1
kind: Service
metadata:
  name: my-mongodb1
  namespace: default
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb1
---
apiVersion: v1
kind: Service
metadata:
  name: my-mongodb2
  namespace: default
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb2