# This workflow publishes the mirrord-ssrv-connections-broken artefacts

name: Build and Publish

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubunut-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        id: cache-maven-repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Run Maven build
        run: mvn -B -U install --file pom.xml -s $GITHUB_WORKSPACE/settings.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Build Docker images
        run: docker build -t nabeelnavro/mirrord-srv-connections-broken:0.1.0 .

      - name: Publish Docker images
        run: docker push nabeelnavro/mirrord-srv-connections-broken:0.1.0
